"""
Dev Agent - Autonomous developer assistant.
Handles project scaffolding and code generation.
"""

import os
import subprocess
from typing import Dict, Any

class DevAgent:
    def __init__(self, workspace_dir: str = "./workspace"):
        self.workspace_dir = os.path.abspath(workspace_dir)
        os.makedirs(self.workspace_dir, exist_ok=True)
        
    def scaffold_project(self, prompt: str, framework: str) -> Dict[str, Any]:
        """
        Scaffolds a project based on the requested framework.
        In a full implementation, this would use LLM to decide folder structure
        or use tools like create-react-app.
        """
        project_name = "new_project" # This could be generated by LLM
        project_path = os.path.join(self.workspace_dir, project_name)
        
        try:
            if framework.lower() in ("react", "nextjs"):
                # Real implementation would call npx create-react-app or create-next-app
                # For safety and speed in this demo, we'll just create a mock folder
                os.makedirs(os.path.join(project_path, "src"), exist_ok=True)
                with open(os.path.join(project_path, "package.json"), "w") as f:
                    f.write(f'{{"name": "{project_name}", "version": "1.0.0", "description": "{prompt}"}}')
                with open(os.path.join(project_path, "src", "index.js"), "w") as f:
                    f.write('console.log("Hello from Wolf AI Dev Agent");')
                    
                msg = f"Successfully scaffolded {framework} project at {project_path}"
                
            elif framework.lower() == "python":
                os.makedirs(os.path.join(project_path, "src"), exist_ok=True)
                with open(os.path.join(project_path, "requirements.txt"), "w") as f:
                    f.write("# Generated dependencies\n")
                with open(os.path.join(project_path, "src", "main.py"), "w") as f:
                    f.write('def main():\n    print("Hello from Wolf AI Dev Agent")\n\nif __name__ == "__main__":\n    main()\n')
                    
                msg = f"Successfully scaffolded {framework} project at {project_path}"
                
            else:
                # Default to HTML/JS
                os.makedirs(project_path, exist_ok=True)
                with open(os.path.join(project_path, "index.html"), "w") as f:
                    f.write(f'<!DOCTYPE html><html><head><title>{project_name}</title></head><body><h1>{prompt}</h1></body></html>')
                    
                msg = f"Successfully scaffolded {framework} HTML project at {project_path}"
                
            return {
                "success": True,
                "message": msg,
                "data": {"path": project_path, "framework": framework}
            }
        except Exception as e:
            return {"success": False, "message": f"Dev Agent Error: {e}"}

# Global instance
dev_agent = DevAgent()
